# Site settings
name: L N S S Ravi Teja
title: Ravi Teja | Full stack Software Engineer
description: Design-minded Full stack software engineer focused on building beautiful interfaces and scalable applications
url: https://bchiang7.github.io/
baseurl: ''
email: ravitejal.creator@gmail.com
cover: https://bchiang7.github.io/img/og.png
logo: https://cdn-icons-png.flaticon.com/512/4019/4019998.png
resume: https://drive.google.com/file/d/1xQhWyxZQJ8s2zd9jK4NQ8NINP7aKnT94/view?usp=sharing
social:
  - title: email
    url: mailto:ravitejal.creator@gmail.com
  - title: twitter
    url: https://twitter.com/creatorworld22
  - title: instagram
    url: https://instagram.com/tej.artfinity
  - title: github
    url: https://github.com/ravitejalakkoju
  - title: linkedin
    url: https://www.linkedin.com/in/ravitejalakkoju

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap